# This GitHub Actions workflow is designed to make a scheduled HTTP POST request
# every 15 minutes. It can also be manually triggered through the GitHub UI.
# It's intended to interact with a scheduling service hosted at mytrafficwizard.onrender.com.

name: Scheduled HTTP Request with HTTP Client

on:
  schedule:
    - cron: '*/12 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allow for manual triggering in GitHub

jobs:
  httpRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Log Start Message
        run: |
          echo "Scheduled HTTP Request initiated at $(date)"
          echo "Initiating scheduler......"

      - name: Initiate Scheduler
        uses: actions/http-client@v1
        with:
          url: 'https://mytrafficwizard.onrender.com/schedule'
          method: 'POST'
          headers: '{"Content-Type": "application/json"}'

      - name: Log Result
        run: |
          echo "Attempt details:\n ${{ steps.httpRequest.outputs.response }}"
