#written by: Tyler Anderson
# tested by: Team
# debugged by: Team

# Run Integration Tests
#
# This GitHub Actions workflow is triggered manually via workflow_dispatch. It is configured to perform
# integration testing on the latest Ubuntu runner environment. It aims to verify the interactions between
# integrated modules of the application within a Node.js environment.
#
# Jobs:
# - integration-tests: Defines the job that runs on an Ubuntu latest environment.
#   Steps:
#   - Checkout repository: Ensures the latest version of the code is used for testing by cloning the repo.
#   - Set up Node.js: Prepares the Node.js environment specified by version 20.11.0 to ensure consistency across test runs.
#   - Install dependencies: Installs all Node.js dependencies necessary for running the integration tests.
#   - Run Integration Tests: Executes the integration tests specified in the tests/integration directory. This step is configured to continue even if errors occur.
#   - Upload HTML Integration Test Report: Saves the generated HTML integration test reports as an artifact for later review, aiding in troubleshooting and validation of test results.
#
# Usage:
# This workflow can be initiated manually from the GitHub repository's Actions tab, providing flexibility in when integration tests are conducted.

name: Run Integration Tests

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}
      DISCORD_API_TOKEN: ${{ secrets.DISCORD_API_TOKEN }}
      GMAILAPPPASSWORD: ${{ secrets.GMAILAPPPASSWORD }}
      GMAILUSER: ${{ secrets.GMAILUSER }}
      SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      TOMMORROW_IO_API_KEY: ${{ secrets.TOMMORROW_IO_API_KEY }}
      TOMMORROW_IO_API_KEY_TEST: ${{ secrets.TOMMORROW_IO_API_KEY_TEST }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'  

    - name: Install dependencies
      run: npm install 

    - name: Run Integration Tests
      run: npm test tests/integration
      continue-on-error: true

    - name: Upload HTML Integration Test Report
      uses: actions/upload-artifact@v2
      with:
        name: integration-test-report
        path: ./tests/reports/test-report.html
