name: Run Unit Tests

on:
  workflow_dispatch:  

jobs:
  unit-tests:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'  

    - name: Install dependencies
      run: npm install 

    - name: Run Unit Tests
      run: npm test tests/unit
      continue-on-error: true

    - name: Upload HTML Unit Test Report
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-report
        path: ./tests/reports/test-report.html